# NumPy Assignment - Questions

Some of the questions can have topics which were not covered in the class. But you can simply google those topics/functions and solve the assignment.

In [135]:
import numpy as np

### 1.  Create a 2x2x2 3-D array containing total 8 elements.

In [136]:
a=np.asanyarray([[[1,2],[3,4]],[[1,2],[3,4]]])
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(2, 2, 2)
3
8
int32


### 2.  Replace the 1st element of the above 3-D array with 10

In [137]:
a[0][0][0]=10
a

array([[[10,  2],
        [ 3,  4]],

       [[ 1,  2],
        [ 3,  4]]])

### 3.  Check the shape and dimensions of the above 3-D array

In [138]:
print(a.shape)
print(a.ndim)

(2, 2, 2)
3


### 4. Export the above array

In [139]:
np.save('array1.npy',a)

### 5. Import the array from given url

``` url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' ```

In [140]:
import pandas as pd

iris=pd.read_csv(r'C:\Users\Jay Patel\OneDrive\Desktop\Machine Learning Plus\Numpy and Pandas\wk03_notebooks\iris.data',delimiter=',')
iris
array = np.asanyarray(iris)
array

array([[4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iris-setosa'],
       [5.1, 3.3, 1.7, 0.5, 'Iri

### 6. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10. 

In [67]:
np.random.rand(5,3)

array([[0.11511917, 0.52748442, 0.54848879],
       [0.22221909, 0.84359264, 0.52500859],
       [0.71941163, 0.5652928 , 0.14576256],
       [0.34393409, 0.41081238, 0.46451186],
       [0.97214707, 0.13923671, 0.79943784]])

In [68]:
np.random.randint(5,10,size=(5,3)) + np.random.rand(5,3)

array([[9.76492898, 9.79683998, 8.48374707],
       [5.82187569, 8.71168209, 6.29239444],
       [9.56852374, 6.29028718, 7.16012518],
       [5.76974369, 5.97529998, 6.29329185],
       [9.05690263, 6.72262898, 9.62262342]])

In [37]:
np.random.uniform(5,10,size=(5,3))

array([[6.91632604, 9.35928554, 7.82838371],
       [9.63828967, 9.17964218, 7.07217498],
       [8.13228787, 5.48416271, 5.10844661],
       [9.49510624, 9.04338904, 7.51833622],
       [5.7808111 , 9.32426047, 5.8368435 ]])

### 7. Insert np.nan values at 20 random positions in iris_2d dataset

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```



In [71]:
import pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [141]:
iris_2d

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [nan, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, nan, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, nan, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [4.3, 3. , 1.1, 0.1, nan],
       [5.8, 4. , 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, 0.3, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, 3.4, 1.7, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , 0.2, nan],
       [5.1, nan, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, 0.2, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3

In [142]:
iris_2d.shape

(150, 5)

In [73]:
i,j = np.where(iris_2d)
i,j

(array([  0,   0,   0,   0,   1,   1,   1,   1,   2,   2,   2,   2,   3,
          3,   3,   3,   4,   4,   4,   4,   5,   5,   5,   5,   6,   6,
          6,   6,   7,   7,   7,   7,   8,   8,   8,   8,   9,   9,   9,
          9,  10,  10,  10,  10,  11,  11,  11,  11,  12,  12,  12,  12,
         13,  13,  13,  13,  14,  14,  14,  14,  15,  15,  15,  15,  16,
         16,  16,  16,  17,  17,  17,  17,  18,  18,  18,  18,  19,  19,
         19,  19,  20,  20,  20,  20,  21,  21,  21,  21,  22,  22,  22,
         22,  23,  23,  23,  23,  24,  24,  24,  24,  25,  25,  25,  25,
         26,  26,  26,  26,  27,  27,  27,  27,  28,  28,  28,  28,  29,
         29,  29,  29,  30,  30,  30,  30,  31,  31,  31,  31,  32,  32,
         32,  32,  33,  33,  33,  33,  34,  34,  34,  34,  35,  35,  35,
         35,  36,  36,  36,  36,  37,  37,  37,  37,  38,  38,  38,  38,
         39,  39,  39,  39,  40,  40,  40,  40,  41,  41,  41,  41,  42,
         42,  42,  42,  43,  43,  43,  43,  44,  44

In [75]:
# Method-1
iris_2d[np.random.choice(i,30),np.random.choice(j,30)]=np.nan

In [80]:
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, nan, nan],
       [nan, nan, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, nan, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, nan, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, nan, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, nan],
       [4.3, nan, 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [nan, 3.9, 1.3, 0.4],
       [5.1, nan, nan, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, nan, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [nan, 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, nan, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [nan, 3

In [81]:
# Method-2
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, nan, nan],
       [nan, nan, 1.5, 0.2],
       [nan, 3.6, 1.4, 0.2],
       [5.4, 3.9, nan, 0.4],
       [4.6, nan, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, nan, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, nan, nan],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, nan],
       [4.3, nan, 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [nan, 4.4, 1.5, 0.4],
       [nan, 3.9, 1.3, 0.4],
       [5.1, nan, nan, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, nan, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [nan, 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, nan, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [nan, 3

### 8.  Find out if iris_2d has any missing values

``` 
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
````


In [88]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
np.isnan(iris_2d).any()

False

### 9.  Find the number and position of missing values in iris_2d's sepallength (1st column)

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan 

````


In [97]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
total_missing_value = np.isnan(iris_2d[:,0]).sum()
print(total_missing_value)
position_of_missing_value = np.where(np.isnan(iris_2d[:, 0]))
position_of_missing_value

5


(array([ 1, 26, 29, 52, 53], dtype=int64),)

### 10. Select the rows of iris_2d that does not have any nan value.

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

```

In [101]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d

any_nan_row = np.array([np.any(np.isnan(row))for row in iris_2d])
iris_2d[any_nan_row][:5]


array([[4.8, 3.1, nan, 0.2],
       [nan, 3.4, 1.5, 0.4],
       [5.5, 4.2, 1.4, nan],
       [5.5, 3.5, 1.3, nan],
       [5.1, 3.8, 1.6, nan]])

### 11. Find mean of every row in iris_2d array

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan 

````

In [105]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan 
np.nanmean(iris_2d,axis=1)

array([2.55      , 2.375     , 2.35      , 2.35      , 2.55      ,
       2.85      , 2.76666667, 2.525     , 2.225     , 2.4       ,
       2.7       , 2.5       , 2.325     , 2.125     , 2.8       ,
       3.        , 2.75      , 2.575     , 3.73333333, 2.675     ,
       2.675     , 2.675     , 2.35      , 2.65      , 2.575     ,
       2.45      , 2.6       , 2.6       , 2.55      , 2.425     ,
       2.425     , 2.675     , 2.725     , 2.825     , 2.4       ,
       2.4       , 2.625     , 2.4       , 2.225     , 2.55      ,
       2.525     , 2.1       , 2.275     , 2.675     , 2.8       ,
       2.375     , 2.675     , 2.66666667, 2.675     , 2.475     ,
       4.075     , 3.9       , 4.1       , 2.53333333, 3.85      ,
       3.575     , 4.2       , 2.9       , 3.85      , 3.3       ,
       2.875     , 3.65      , 3.3       , 3.775     , 3.26666667,
       3.9       , 3.65      , 3.4       , 3.6       , 3.06666667,
       3.925     , 4.3       , 3.8       , 3.7       , 3.725  

### 12. Get the common items between a and b

```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [106]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

### 13. From array a remove all items present in array b

```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

In [107]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 14. Find the mean, median, standard deviation of iris's sepallength (1st column)

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [127]:
summ, mean,standard = np.nanmean(iris_2d[:,0]),np.nanmedian(iris_2d[:,0]),np.nanstd(iris_2d[:,0])
print(summ, mean,standard)

5.847297297297297 5.8 0.8301290965986691


### 15. Fill the missing values with median of the columns in iris dataset

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [143]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

np.nanmedian(iris_2d,axis=1).round(2)

array([2.45, 2.2 , 2.25, 2.3 , 1.4 , 2.8 , 2.4 , 2.45, 2.15, 2.3 , 2.6 ,
       2.5 , 2.2 , 2.05, 2.6 , 2.95, 2.6 , 2.45, 2.75, 2.65, 2.55, 2.6 ,
       2.3 , 2.5 , 2.65, 1.6 , 1.6 , 2.5 , 2.4 , 2.4 , 2.35, 2.45, 2.8 ,
       2.8 , 2.3 , 1.2 , 2.4 , 2.3 , 1.3 , 2.45, 2.4 , 1.3 , 2.25, 2.55,
       2.85, 1.4 , 2.7 , 2.3 , 2.6 , 1.4 , 3.95, 3.85, 4.  , 3.15, 3.7 ,
       3.65, 4.  , 2.85, 3.75, 3.3 , 2.  , 3.6 , 3.1 , 3.8 , 3.25, 3.75,
       3.75, 3.4 , 3.35, 4.05, 4.  , 3.4 , 3.7 , 3.75, 3.6 , 3.7 , 3.8 ,
       4.  , 3.7 , 3.05, 3.1 , 3.05, 3.3 , 3.9 , 3.75, 3.95, 3.9 , 3.35,
       3.55, 3.25, 3.5 , 3.8 , 3.3 , 2.8 , 3.45, 3.6 , 3.55, 3.6 , 2.75,
       3.45, 4.65, 3.9 , 4.45, 4.25, 4.4 , 4.8 , 3.5 , 4.6 , 4.15, 4.85,
       4.15, 4.  , 4.25, 3.75, 3.95, 4.25, 4.25, 5.25, 4.75, 3.6 , 5.7 ,
       3.85, 4.75, 4.9 , 3.3 , 4.6 , 3.8 , 4.9 , 4.2 , 4.4 , 4.45, 5.1 ,
       4.2 , 3.95, 4.1 , 4.55, 3.4 , 4.3 , 4.8 , 4.25, 5.6 , 4.1 , 3.9 ,
       4.55, 4.5 , 5.2 , 3.75, 4.1 , 4.4 , 4.05])

### 16. Flatten the 3 D array (optional)

```
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
```

In [50]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
array_3d.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

### 17. Create an equally spaced numpy array of length 20 having values between 1 and 100. Print the stepsize between two values as well.

In [54]:
a=np.linspace(1,100,20)
a

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

### 18. Stack the arrays a and b horizontally. (optional)

```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [147]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 19. Split the iris dataset into multiple small arrays having 10 rows each (optional)

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])
```

In [148]:
np.vsplit(iris_2d,10)

[array([[5.1, 3.5, 1.4, 0.2, nan],
        [4.9, 3. , 1.4, 0.2, nan],
        [4.7, 3.2, 1.3, 0.2, nan],
        [4.6, 3.1, 1.5, 0.2, nan],
        [nan, 3.6, 1.4, 0.2, nan],
        [5.4, 3.9, 1.7, 0.4, nan],
        [4.6, 3.4, 1.4, 0.3, nan],
        [5. , 3.4, 1.5, 0.2, nan],
        [4.4, 2.9, 1.4, 0.2, nan],
        [4.9, 3.1, 1.5, 0.1, nan],
        [5.4, 3.7, 1.5, 0.2, nan],
        [4.8, 3.4, 1.6, 0.2, nan],
        [4.8, 3. , 1.4, 0.1, nan],
        [4.3, 3. , 1.1, 0.1, nan],
        [5.8, 4. , 1.2, 0.2, nan]]),
 array([[5.7, 4.4, 1.5, 0.4, nan],
        [5.4, 3.9, 1.3, 0.4, nan],
        [5.1, 3.5, 1.4, 0.3, nan],
        [5.7, 3.8, 1.7, 0.3, nan],
        [5.1, 3.8, 1.5, 0.3, nan],
        [5.4, 3.4, 1.7, 0.2, nan],
        [5.1, 3.7, 1.5, 0.4, nan],
        [4.6, 3.6, 1. , 0.2, nan],
        [5.1, 3.3, 1.7, 0.5, nan],
        [4.8, 3.4, 1.9, 0.2, nan],
        [5. , nan, 1.6, 0.2, nan],
        [5. , nan, 1.6, 0.4, nan],
        [5.2, 3.5, 1.5, 0.2, nan],
        [5.2, 3.4,

### Cars 93 data

In [149]:
import numpy as np

dt = np.dtype([("Manufacturer", np.unicode_, 16),
               ("Model", np.unicode_, 16),
               ("Type", np.unicode_, 16),
               ("Min_Price", np.float64),
               ("Price", np.float64),
               ("Max_Price", np.float64),
               ("MPG_city", np.float64),
               ("MPG_highway", np.float64),
               ("AirBags", np.unicode_, 16)])

dt

data = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Cars93.csv', 
                     delimiter=",", 
                     dtype=dt,
                     skip_header=1,
                     usecols=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
data

array([('"Acura"', '"Integra"', '"Small"', 12.9, 15.9, 18.8, 25., 31., '"None"'),
       ('"Acura"', '"Legend"', '"Midsize"', 29.2, 33.9, 38.7, 18., 25., '"Driver & Passen'),
       ('"Audi"', '"90"', '"Compact"', 25.9, 29.1, 32.3, 20., 26., '"Driver only"'),
       ('"Audi"', '"100"', '"Midsize"', 30.8, 37.7, 44.6, 19., 26., '"Driver & Passen'),
       ('"BMW"', '"535i"', '"Midsize"', 23.7, 30. , 36.2, 22., 30., '"Driver only"'),
       ('"Buick"', '"Century"', '"Midsize"', 14.2, 15.7, 17.3, 22., 31., '"Driver only"'),
       ('"Buick"', '"LeSabre"', '"Large"', 19.9, 20.8, 21.7, 19., 28., '"Driver only"'),
       ('"Buick"', '"Roadmaster"', '"Large"', 22.6, 23.7, 24.9, 16., 25., '"Driver only"'),
       ('"Buick"', '"Riviera"', '"Midsize"', 26.3, 26.3, 26.3, 19., 27., '"Driver only"'),
       ('"Cadillac"', '"DeVille"', '"Large"', 33. , 34.7, 36.3, 16., 25., '"Driver only"'),
       ('"Cadillac"', '"Seville"', '"Midsize"', 37.5, 40.1, 42.7, 16., 25., '"Driver & Passen'),
       ('"Che

### 20. Sort the cars93 dataset based on Price column.

In [151]:
np.argsort(data['Price'])

array([30, 43, 52, 38, 79, 82, 72, 87, 22, 83, 44, 45, 31, 61, 80, 73, 78,
       23, 32, 12, 53, 63, 41, 28, 39, 24, 11, 67, 46, 34, 59, 71, 60, 13,
       26, 64,  5, 20,  0, 33, 14, 15, 68, 54, 16, 42, 74, 85, 19, 84, 75,
       17, 25, 55, 65, 29, 69, 81, 88, 40, 35, 89, 36, 70,  6, 37, 66, 91,
       86, 90,  7, 76, 27, 62,  8, 92, 48, 77,  2, 21,  4, 57, 56,  1, 50,
        9, 49, 51,  3, 18, 10, 47, 58], dtype=int64)

### 21. Sort the cars93 dataset based on two columns - Min_Price column first and Max_Price second.

In [153]:
np.argsort(data[['Min_Price','Max_Price']])

array([38, 43, 30, 79, 82, 52, 61, 83, 22, 28, 72, 31, 23, 41, 11, 87, 63,
       44, 45, 78, 73, 32, 80, 33, 53, 12, 71, 39, 24, 46, 34,  0, 67, 64,
       59, 13, 14, 25, 42, 74,  5, 68, 84, 54, 20, 35, 15, 16, 26, 60, 85,
       75, 36, 81, 55, 88, 65, 40, 29, 89, 17, 19, 27, 86, 76, 69, 70,  6,
       37, 77, 66, 91, 62,  7, 90,  4, 92,  2,  8, 48, 57,  1, 21,  3, 56,
        9, 50, 51, 18, 49, 10, 58, 47], dtype=int64)

### 22. Extract various time values from the date 

```
today = np.datetime64('2021-09-28T07:30')
```

In [163]:
today = np.datetime64('2021-09-28T07:30')
print('year:', np.datetime64(today,'Y'))
print('Month:', np.datetime64(today,'M'))
print('day:', np.datetime64(today,'D'))
print('second:', np.datetime64(today,'s'))

year: 2021
Month: 2021-09
day: 2021-09-28
second: 2021-09-28T07:30:00


### 23. Add 5 business days and regular days to the date

```
today = '2021-09-28'
```

In [173]:
np.timedelta64(5,'D') 

numpy.timedelta64(5,'D')

In [174]:
np.datetime64(today,'D')

numpy.datetime64('2021-09-28')

In [171]:
today = '2021-09-28'
print(np.busday_offset(today,5))
print(np.datetime64(today,'D') + np.timedelta64(5,'D') )

2021-10-05
2021-10-03


### 24. Find out the business days between two dates

```
day1 = '2021-09-28'
day2 = '2021-10-28'
```

In [175]:
day1 = '2021-09-28'
day2 = '2021-10-28'
np.busday_count(day1,day2)

22

### 25. Create a function to compute the coeffecient of variation and apply it row wise in the iris dataset (optional)

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])
```

In [187]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

In [191]:
def cv(x):
    return np.std(x) / np.mean(x)


print('Row wise: \n', np.apply_along_axis(cv, 1, arr=iris_2d), '\n')


Row wise: 
 [0.74017985 0.7427582  0.73612102 0.70470192 0.73234704 0.67788348
 0.69149057 0.72345011 0.70946849 0.7465197  0.74027763 0.69856997
 0.75690065 0.76777664 0.79378967 0.71219535 0.72659059 0.72100045
 0.71383837 0.70354654 0.72458541 0.6864548  0.76920117 0.65224098
 0.66495995 0.72413041 0.67280214 0.73329523 0.74895801 0.69639156
 0.7060915  0.71193855 0.74323252 0.75023165 0.7465197  0.77055175
 0.77763523 0.7465197  0.72076703 0.72971741 0.72831188 0.74077853
 0.71648015 0.63517033 0.64037218 0.71478257 0.70997288 0.71553922
 0.73464127 0.73917036 0.50392714 0.45975439 0.4914498  0.49063249
 0.48956044 0.46696325 0.43623505 0.48826904 0.51179378 0.42693948
 0.5271459  0.44197989 0.5725589  0.47140969 0.46075669 0.49620519
 0.42377283 0.51993146 0.51855985 0.50928103 0.39690269 0.49456478
 0.5        0.50236839 0.50308718 0.4960631  0.51682166 0.46501649
 0.45335558 0.53079024 0.5111071  0.52668762 0.49521936 0.4604441
 0.41247896 0.41426188 0.48153401 0.54000324 0.4485

### 26. Multiply given two matrix element wise (optional)

```
np.random.seed(100)
A = np.arange(25).reshape(5,5)
B = np.random.randint(0, 9, (5,5))
```

In [193]:
np.random.seed(100)
A = np.arange(25).reshape(5,5)
B = np.random.randint(0, 9, (5,5))
A*B

array([[  0,   8,   6,  21,  28],
       [  0,  24,  14,  40,  18],
       [ 20,  22,  12,   0, 112],
       [ 60,   0, 102,  36,  76],
       [ 20, 105,  66,  92,  96]])

### 27. Take inverse of matrix A (optional)

```
# Input
np.random.seed(100)
A = np.random.randint(0, 9, (5,5))
```

In [195]:
np.random.seed(100)
A = np.random.randint(0, 9, (5,5))
print(A)
np.linalg.inv(A)

[[8 8 3 7 7]
 [0 4 2 5 2]
 [2 2 1 0 8]
 [4 0 6 2 4]
 [1 5 3 4 4]]


array([[ 0.1352657 , -0.12801932, -0.05555556,  0.03019324, -0.09178744],
       [ 0.0257649 , -0.42914654, -0.12962963, -0.12520129,  0.55394525],
       [-0.07729469, -0.21256039, -0.11111111,  0.12560386,  0.33816425],
       [ 0.02254428,  0.56199678,  0.07407407,  0.04669887, -0.51529791],
       [-0.03059581,  0.16586151,  0.18518519,  0.00805153, -0.15780998]])