In [1]:
import numpy as np


- ITERATE OVER 1-D ARRAY

In [2]:
array1=np.array([1,2,3,4,5])
i=0
for x in array1:
    print(x)
    i+=1
    print(i)

1
1
2
2
3
3
4
4
5
5


- ITERATE OVER 2-D ARRAY

In [3]:
array2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
i=0
for x in array2:
    print(x)
    i+=1
    print(i)

[1 2 3 4 5]
1
[ 6  7  8  9 10]
2


In [4]:
array2=np.array([[1,2,3,4,5],[6,7,8,9,10],[10,11,12,13,14]])
i=0
for x in array2:
    print(x)
    i+=1
    print(i)

[1 2 3 4 5]
1
[ 6  7  8  9 10]
2
[10 11 12 13 14]
3


- Loop is only iterating for 2 times and not goining into the third layer of the two dimensional matrix

- for this we need to implement 2 for loops 

- so, if matrix is of one dimensional then we use 1 for loop

- if matrix is of two dimensional then we have to use 2 for loop and so on...

- Iterate by elements in a 2- dimensional array

In [5]:
array3=np.array([[1,2,3,4,5],[6,7,8,9,10],[10,11,12,13,14]])
for i in array3:
    for j in i:
        print(j)


1
2
3
4
5
6
7
8
9
10
10
11
12
13
14


- Iterate over elements in a 3- dimensional array

In [6]:
array4=np.array([[[1,2,3,4,5],[6,7,8,9,10],[10,11,12,13,14],[15,16,17,18,19]]])
array4


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [8]:
i=0
for x in array3:
    print(x)
    i+=1
    print(i)

[1 2 3 4 5]
1
[ 6  7  8  9 10]
2
[10 11 12 13 14]
3


- Here, also for loop is goining into the 2st layer and not finishing the 3rd layer

- Iterate by elements in a 3- dimensional array

In [9]:
for i in array4:
    for j in i:
        for x in j:
            print(x)
    

1
2
3
4
5
6
7
8
9
10
10
11
12
13
14
15
16
17
18
19


- using nditer and loop through the array

In [11]:
array6=np.array([[[1,2,3,4,5],[6,7,8,9,10],[10,11,12,13,14],[15,16,17,18,19]]])
for i in np.nditer(array6):
    print(i)

1
2
3
4
5
6
7
8
9
10
10
11
12
13
14
15
16
17
18
19


# Manipulation

In [14]:
m_array1=np.arange(25)
print(m_array1)
m_array1.reshape(5,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

- Reshape higher dimension to 1-d

In [16]:
m_array2=np.array([[1,2,3],[4,5,6]])
m_array2.flatten()

array([1, 2, 3, 4, 5, 6])

# Transpose

In [17]:
print(m_array2.T)

[[1 4]
 [2 5]
 [3 6]]


In [18]:
print(m_array1.T)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


# ROLL AXIS

Roll the specified axis backwards, until it lies in a given position.


In [21]:
m_array2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
print(np.rollaxis(m_array2,1))

[[1 4]
 [2 5]
 [3 6]]


In [22]:
m_array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
array4

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [26]:
print(np.rollaxis(array4,1))

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[10 11 12 13 14]]

 [[15 16 17 18 19]]]


In [27]:
print(np.rollaxis(array4,2))

[[[ 1  6 10 15]]

 [[ 2  7 11 16]]

 [[ 3  8 12 17]]

 [[ 4  9 13 18]]

 [[ 5 10 14 19]]]


# Random Numbers

In [30]:
from numpy import random
random.rand()

0.06655546149120695

In [31]:
random.randint(25,size=(5))

array([ 5,  8, 24, 12,  5])

# Random array with specific distribution

In [32]:
r_arrays=random.choice([1,2,3,4,5],p=[.1,.2,.4,.2,.1],size=(100))

In [33]:
r_arrays

array([3, 2, 4, 3, 1, 3, 3, 5, 3, 3, 1, 3, 5, 4, 3, 5, 2, 3, 1, 2, 5, 3,
       2, 3, 2, 2, 3, 4, 4, 3, 5, 3, 1, 3, 3, 4, 5, 3, 4, 4, 5, 3, 3, 4,
       4, 2, 3, 2, 2, 3, 3, 3, 3, 2, 3, 5, 1, 5, 2, 2, 3, 2, 3, 3, 2, 3,
       3, 4, 3, 5, 3, 4, 4, 2, 2, 3, 4, 5, 2, 1, 3, 2, 2, 3, 2, 4, 2, 3,
       3, 3, 2, 4, 3, 2, 2, 3, 4, 3, 3, 3])

- 1 will repeated 0.1 times, 2 for .2 times and so on